THU-DSP-LAB/llvm-project

- libclc/riscv32/lib/crt0.S
> set mstatus in crt0.S to enable F extension

- libclc/riscv32/lib/crt0.S
> [VENTUS][RISCV][fix] Fix tp initial value bugs

- README.md
add packages needed for other repositories and modify branch for driver-repository.
> [VENTUS][RISCV][doc] Update README.md

- libclc/riscv32/lib/workitem/workitem.S
- llvm/lib/Target/RISCV/RISCVFrameLowering.cpp
> [VENTUS][fix] Fix getStackSize calculation bugs

- llvm/lib/Target/RISCV/VentusInsertJoinToVBranch.cpp
> [VENTUS][fix] Fix insert join instruction bug

- llvm/lib/Target/RISCV/VentusInstrInfo.td
- llvm/lib/Target/RISCV/VentusInstrInfoF.td
Detailed issue can be seen in: https://github.com/THU-DSP-LAB/llvm-project/issues/22
> [VENTUS][fix] Fix illegal bitcast

- libclc/riscv32/lib/workitem/workitem.S
> [#36][fix] fix the bug that the calclation of global id is err

- clang/include/clang/Basic/BuiltinsRISCV.def
- clang/lib/CodeGen/CGBuiltin.cpp
- clang/lib/Headers/opencl-c.h
- clang/test/CodeGenOpenCL/barrier.cl
Support barrier with memory scope parameter.
> [#60][feat] Support barrier with memory scope parameter

- libclc/generic/include/clc/async/gentype.inc
> [VENTUS][fix] Add libclc function parameter vector size equal 3 support

- libclc/generic/lib/shared/clamp.inc
> [VENTUS][fix] Fix clamp function

- llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp
- llvm/lib/Target/RISCV/RISCVInstrInfo.cpp
- llvm/lib/Target/RISCV/RISCVMakeCompressible.cpp
- llvm/lib/Target/RISCV/RISCVMergeBaseOffset.cpp
- llvm/lib/Target/RISCV/VentusInstrInfoF.td
- llvm/lib/Target/RISCV/VentusInstrInfoV.td
- llvm/test/CodeGen/RISCV/VentusGPGPU/addr-space.ll
- llvm/test/CodeGen/RISCV/VentusGPGPU/addr-space2.ll
- llvm/test/CodeGen/RISCV/VentusGPGPU/bitcast.ll
- llvm/test/CodeGen/RISCV/VentusGPGPU/branch.ll
- llvm/test/CodeGen/RISCV/VentusGPGPU/builtin-noverify.ll
- llvm/test/CodeGen/RISCV/VentusGPGPU/builtin.ll
- llvm/test/CodeGen/RISCV/VentusGPGPU/calling-convention.ll
- llvm/test/CodeGen/RISCV/VentusGPGPU/float.ll
- llvm/test/CodeGen/RISCV/VentusGPGPU/function-call.ll
- llvm/test/CodeGen/RISCV/VentusGPGPU/resource-usage.ll
- llvm/test/CodeGen/RISCV/VentusGPGPU/var-arg.ll
- llvm/test/CodeGen/RISCV/VentusGPGPU/vbranch-join.ll
https://github.com/THU-DSP-LAB/llvm-project/issues/44
> [VENTUS][fix] Remove instructions not supported by hardware

- llvm/lib/Target/RISCV/RISCVAsmPrinter.cpp
- llvm/lib/Target/RISCV/RISCVFrameLowering.cpp
- llvm/lib/Target/RISCV/RISCVRegisterInfo.cpp
- llvm/lib/Target/RISCV/RISCVRegisterInfo.h
- llvm/lib/Target/RISCV/RISCVSubtarget.h
- llvm/lib/Target/RISCV/VentusProgramInfo.h
1. Fix the bug of repeated calculation of register resources.
2. Add resource calculation with stack register.
> [VENTUS][fix] Fix the mechanism of statistical register resources

- llvm/lib/Target/RISCV/RISCVISelLowering.cpp
- llvm/lib/Target/RISCV/RISCVInstrInfo.cpp
- llvm/lib/Target/RISCV/RISCVRegisterInfo.cpp
- llvm/lib/Target/RISCV/RISCVRegisterInfo.h
- llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp
- llvm/lib/Target/RISCV/VentusInstrInfoF.td
- llvm/lib/Target/RISCV/VentusRegisterInfo.td
1.Kernel function argument is not divergent
2.GPRF32 is not divergent
3.Set PHINode is divergent
4.Add flw/fsw instruction for GPRF32
> [VENTUS][fix] Fix kernel divergent analysis

- llvm/lib/Target/RISCV/RISCVISelLowering.cpp
- llvm/lib/Target/RISCV/RISCVInstrInfo.cpp
- llvm/lib/Target/RISCV/RISCVRegisterInfo.cpp
- llvm/lib/Target/RISCV/RISCVRegisterInfo.h
- llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp
- llvm/lib/Target/RISCV/VentusInstrInfoF.td
- llvm/lib/Target/RISCV/VentusRegisterInfo.td
- llvm/test/CodeGen/RISCV/VentusGPGPU/kernel_args.ll
1.Add a floating add kernel function testcase
2.Remove a comment
> [Ventus][NFC] Add kernel function testcase

- llvm/lib/Target/RISCV/VentusInstrInfoF.td
- llvm/test/CodeGen/RISCV/VentusGPGPU/kernel_args.ll
Replace FLW/FSW instruction with PseudoFLW/PseudoFSW
> [VENTUS][fix] Fix FLW/FSW instruction encoding conflict

- README.md
Explained how to generate ELF file step-by-step.
> [VENTUS][NFC] Add compile guide in README

- libclc/riscv32/lib/SOURCES
- libclc/riscv32/lib/workgroup/wg.h
- libclc/riscv32/lib/workgroup/wganyall.cl
- libclc/riscv32/lib/workgroup/wgbarrier.cl
- libclc/riscv32/lib/workgroup/wgbcast.cl
- libclc/riscv32/lib/workgroup/wgreduce.cl
- libclc/riscv32/lib/workgroup/wgscan.cl
- libclc/riscv32/lib/workgroup/wgscratch.cl
1.Implement barrier and work_group_barrier function with intrinsics.
2.Implement work_group_all and work_group_any function,passed corresponding OPENCL-CTS test.
> [VENTUS][libclc][feat] Add missing workgroup function implementations

- llvm/lib/Target/RISCV/Disassembler/RISCVDisassembler.cpp
> [VENTUS][fix] Disable compress instruction disassemble

- README.md
Some flags are not correct in README
> [NFC][readme] Modify some compiler flags

- .github/CODEOWNERS
- .github/workflows/containers/dockerfiles/ventus_centos.Dockerfile
- README.md
1. Add the dockerfile of centos;
2. Set codeowners;
> [VENTUS][Configuration] Add some configuration

- libclc/generic/lib/misc/shuffle.cl
Passed OPENCL-CTS shuffle_built_in testcase
> [Ventus][fix]Fix libclc shuffle function

- .github/workflows/containers/dockerfiles/ventus_centos.Dockerfile
- README.md
1. Change the registry mirror.
2. Use the system default compiler.
> [ventus][fix] Fix the dockerfile file of centos
